/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dbb.UcitavanjePodesavanja;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import niti.PokreniServer;

/**
 *
 * @author Ivana
 */
public class PodesavanjaForma extends javax.swing.JDialog {

    ServerskaForma sf;
    PokreniServer ps;

    /**
     * Creates new form PodesavanjaForma
     *
     * @param parent
     */
    public PodesavanjaForma(java.awt.Frame parent, boolean modal, PokreniServer ps) {
        super(parent, modal);
        this.ps = ps;
        sf = (ServerskaForma) parent;
        initComponents();
        initUI();
        srediFormu();
    }

    private void initUI() {

        setSize(400, 400);
        centerFrame();
        setTitle("Podesavanja parametara forma");
        //setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    private void centerFrame() {

        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();

        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;
        setLocation(dx, dy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPort = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPromeni = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        txtURL = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        lblValURLPrazan = new javax.swing.JLabel();
        lblValUsernamePrazan = new javax.swing.JLabel();
        lblValPortPrazan = new javax.swing.JLabel();
        lblValPortNijeBroj = new javax.swing.JLabel();
        lblValPortNegativan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortActionPerformed(evt);
            }
        });

        jLabel1.setText("URL");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        jLabel4.setText("Port");

        btnPromeni.setText("Sačuvaj promene");
        btnPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromeniActionPerformed(evt);
            }
        });

        btnOtkazi.setText("Otkaži");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        txtURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtURLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblValUsernamePrazan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUser, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblValURLPrazan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtURL, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblValPortPrazan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPort, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                .addComponent(lblValPortNijeBroj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblValPortNegativan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnPromeni)
                        .addGap(38, 38, 38)
                        .addComponent(btnOtkazi)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValURLPrazan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValUsernamePrazan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValPortPrazan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValPortNijeBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValPortNegativan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPromeni)
                    .addComponent(btnOtkazi))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortActionPerformed

    private void btnPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniActionPerformed
      lblValPortNegativan.setText("");
      lblValPortNijeBroj.setText("");
      lblValPortPrazan.setText("");
      lblValURLPrazan.setText("");
      lblValUsernamePrazan.setText("");
        try {
            boolean test = false;
            String user = txtUser.getText();
            String url = txtURL.getText();
            String pass = txtPassword.getText();
            String port = txtPort.getText();
            int portNumber = 0;
            if (user.isEmpty()) {
                lblValUsernamePrazan.setForeground(Color.red);
                lblValUsernamePrazan.setText("*Username ne moze biti prazan*");
                test = true;
            }
            if (url.isEmpty()) {
                lblValURLPrazan.setForeground(Color.red);
                lblValURLPrazan.setText("*URL ne moze biti prazan*");
                test = true;
            }
            if (port.isEmpty()) {
                lblValPortPrazan.setForeground(Color.red);
                lblValPortPrazan.setText("*Port ne moze biti prazan*");
                test = true;
            }
            if (test == false) {

                try {
                    portNumber = Integer.parseInt(port);

                    if (portNumber < 0) {
                        //JOptionPane.showMessageDialog(this, "Niste uneli pozitivan port!");
                        //return;
                        lblValPortNegativan.setForeground(Color.red);
                        lblValPortNegativan.setText("*Port ne moze biti manji od 0*");
                        test = true;

                    }
                } catch (NumberFormatException ex) {
                    //JOptionPane.showMessageDialog(this, "Niste uneli pravilan port!");
                    //return;
                    lblValPortNijeBroj.setForeground(Color.red);
                    lblValPortNijeBroj.setText("*Port mora sadrzati samo cifre*");
                    test = true;

                }
            } else {
                return;
            }
            if (test == false) {
               

                int brojSluzbenika = Kontroler.getInstance().getListaSluzbenika().size();

                if (brojSluzbenika == 0) {
                    if (ps != null) {
                        ps.interrupt();
                        sf.getBtnZaustavi().setEnabled(false);
                        sf.getBtnPokreni().setEnabled(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Ne mogu se menjati parametri na serveru! Trenutno je povezan sa " + brojSluzbenika + " sluzbenika!");
                    this.dispose();
                    return;
                }

                
                UcitavanjePodesavanja.getInstanca().setProperty("port", (portNumber + ""));
                UcitavanjePodesavanja.getInstanca().setProperty("url", url);
                UcitavanjePodesavanja.getInstanca().setProperty("password", pass);
                UcitavanjePodesavanja.getInstanca().setProperty("username", user);
                JOptionPane.showMessageDialog(this, "Sačuvane promene");
                 this.dispose();
            } else {
                return;
            }
        } catch (IOException ex) {
            Logger.getLogger(PodesavanjaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPromeniActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void txtURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtURLActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnPromeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblValPortNegativan;
    private javax.swing.JLabel lblValPortNijeBroj;
    private javax.swing.JLabel lblValPortPrazan;
    private javax.swing.JLabel lblValURLPrazan;
    private javax.swing.JLabel lblValUsernamePrazan;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtURL;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        try {
            txtURL.setText(UcitavanjePodesavanja.getInstanca().getProperty("url"));
            txtUser.setText(UcitavanjePodesavanja.getInstanca().getProperty("username"));
            txtPassword.setText(UcitavanjePodesavanja.getInstanca().getProperty("password"));
            txtPort.setText(UcitavanjePodesavanja.getInstanca().getProperty("port"));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Ne može da učita podatke!!");
            this.dispose();
            return;
        }
    }
}
