/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domen.Pacijent;
import domen.Pregled;
import domen.Sluzbenik;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;

import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import kontroler.KontrolerKlijent;
import modeli.ModelTabelePacijenata;
import modeli.ModelTabelePregleda;

/**
 *
 * @author Stefan
 */
public class FormaPretraziPacijenta extends JFrame {

    private KontrolerKlijent kontrolerKlijent;
    //private ArrayList<Pregled> listaIzmenjenihPregleda;
    private Sluzbenik ulogovaniSluzbenik;
    private Object lastSelection = null;
    private Object lastSelection2 = null;

    private GlavnaForma gf;

    public JTable getTblPacijenti() {
        return tblPacijenti;
    }

    /**
     * Creates new form FormaPretragaPacijenta
     */
    public FormaPretraziPacijenta(java.awt.Frame parent, boolean modal, Sluzbenik sluzbenik) {
        initComponents();
        tblPacijenti.setRowHeight(20);
        tblIstorijaPregleda.setRowHeight(20);
        this.ulogovaniSluzbenik = sluzbenik;
        initUI();
        tblIstorijaPregleda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblPacijenti.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        this.gf = (GlavnaForma) parent;
        kontrolerKlijent = new KontrolerKlijent();
        
       

        kontrolerKlijent.srediTabeluPacijenata(this, tblPacijenti);

        kontrolerKlijent.pripremiTabeluPacijenataZaSort(this, tblPacijenti, txtPretraziPacijenta);

        ModelTabelePregleda mtpr = new ModelTabelePregleda(new ArrayList());
        tblIstorijaPregleda.setModel(mtpr);
        tblIstorijaPregleda.revalidate();
        tblIstorijaPregleda.repaint();

        tblPacijenti.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                System.out.println("kliknuto u tabelu");
                ModelTabelePregleda mtp = (ModelTabelePregleda)tblIstorijaPregleda.getModel();
                
                kontrolerKlijent.srediTabeluPregleda(tblPacijenti, tblIstorijaPregleda);
             
                }

        });

    }

    private void initUI() {

        setSize(800, 1050);
        centerFrame();
        setTitle("Pacijenti forma");
    }

    private void centerFrame() {

        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();

        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;
        setLocation(dx, dy);
    }

    public FormaPretraziPacijenta() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPretraziPacijenta = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPacijenti = new javax.swing.JTable();
        btnIzmeniPacijenta = new javax.swing.JButton();
        btnDodajNovogPacijenta = new javax.swing.JButton();
        btnObrisiPacijenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnOtkazi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblIstorijaPregleda = new javax.swing.JTable();
        btnZakaziPregled = new javax.swing.JButton();
        btnPrikaziPregled = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtPretraziPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPretraziPacijentaActionPerformed(evt);
            }
        });
        txtPretraziPacijenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPretraziPacijentaKeyTyped(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pacijenti"));

        tblPacijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPacijenti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPacijentiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPacijenti);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnIzmeniPacijenta.setText("Izmeni pacijenta");
        btnIzmeniPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniPacijentaActionPerformed(evt);
            }
        });

        btnDodajNovogPacijenta.setText("Dodaj novog pacijenta");
        btnDodajNovogPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNovogPacijentaActionPerformed(evt);
            }
        });

        btnObrisiPacijenta.setText("Obrisi pacijenta");
        btnObrisiPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPacijentaActionPerformed(evt);
            }
        });

        jLabel1.setText("Pretrazi pacijenta:");

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Istorija pregleda"));

        tblIstorijaPregleda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblIstorijaPregleda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIstorijaPregledaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblIstorijaPregleda);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnZakaziPregled.setText("Zakazi pregled");
        btnZakaziPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZakaziPregledActionPerformed(evt);
            }
        });

        btnPrikaziPregled.setText("Prikaži pregled");
        btnPrikaziPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziPregledActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnZakaziPregled, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209)
                .addComponent(btnPrikaziPregled)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(btnOtkazi))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnIzmeniPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnDodajNovogPacijenta)
                        .addGap(64, 64, 64)
                        .addComponent(btnObrisiPacijenta))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPretraziPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretraziPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeniPacijenta)
                    .addComponent(btnDodajNovogPacijenta)
                    .addComponent(btnObrisiPacijenta))
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZakaziPregled)
                    .addComponent(btnPrikaziPregled))
                .addGap(33, 33, 33)
                .addComponent(btnOtkazi)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajNovogPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNovogPacijentaActionPerformed
        // TODO add your handling code here:
        FormaDodajPacijenta fdp = new FormaDodajPacijenta(this);

    }//GEN-LAST:event_btnDodajNovogPacijentaActionPerformed

    private void btnIzmeniPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniPacijentaActionPerformed
        // TODO add your handling code here:
        int red = tblPacijenti.getSelectedRow();
        if (red != -1) {
            ModelTabelePacijenata mtp = (ModelTabelePacijenata) tblPacijenti.getModel();
            ArrayList<Pacijent> listaPacijenata = mtp.getListaPacijenata();
            Pacijent p = listaPacijenata.get(tblPacijenti.convertRowIndexToModel(red));
            Pacijent pacijent = kontrolerKlijent.ucitajPacijenta(p);
            if (pacijent!= null){
            FormaDodajPacijenta fdp = new FormaDodajPacijenta(pacijent, this);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Niste izabrali pacijenta");
            return;
        }
    }//GEN-LAST:event_btnIzmeniPacijentaActionPerformed

    private void btnObrisiPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPacijentaActionPerformed
        // TODO add your handling code here:
        int red = tblPacijenti.getSelectedRow();
        if (red != -1) {
            kontrolerKlijent.obrisiPacijenta(this, tblIstorijaPregleda, red, tblPacijenti);
            resetSelection();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nije odabran pacijent!");
            return;
        }
    }//GEN-LAST:event_btnObrisiPacijentaActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        // TODO add your handling code here:
        dispose();

        gf.setVisible(true);
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void txtPretraziPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPretraziPacijentaActionPerformed

        resetSelection();
        tblPacijenti.clearSelection();
        tblIstorijaPregleda.setModel(new ModelTabelePregleda());
    }//GEN-LAST:event_txtPretraziPacijentaActionPerformed

    public JTable getTblIstorijaPregleda() {
        return tblIstorijaPregleda;
    }

    private void btnZakaziPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZakaziPregledActionPerformed
        // TODO add your handling code here:
        int red = tblPacijenti.getSelectedRow();
        if (red != -1) {
            ModelTabelePacijenata mtp = (ModelTabelePacijenata) tblPacijenti.getModel();
            Pacijent pacijent = mtp.getPacijent(tblPacijenti.convertRowIndexToModel(red));
            FormaZakaziPregled fzp = new FormaZakaziPregled(pacijent, this, ulogovaniSluzbenik);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Niste izabrali pacijenta");
            return;
        }

    }//GEN-LAST:event_btnZakaziPregledActionPerformed

    private void btnPrikaziPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziPregledActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int red = tblIstorijaPregleda.getSelectedRow();
        if (red != -1) {
            ModelTabelePregleda mtp = (ModelTabelePregleda) tblIstorijaPregleda.getModel();
            ArrayList<Pregled> listaPregleda = mtp.getListaPregleda();
            Pregled p = listaPregleda.get(tblIstorijaPregleda.convertRowIndexToModel(red));
            Pregled pregled = kontrolerKlijent.ucitajPregled(p);
if (pregled!= null){            
            FormaUcitajPregled fup = new FormaUcitajPregled(pregled, this);
            fup.setVisible(true);
}

           

        } else {
            JOptionPane.showMessageDialog(rootPane, "Niste izabrali pregled");
            return;
        }

      

    }//GEN-LAST:event_btnPrikaziPregledActionPerformed


    private void tblPacijentiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPacijentiMouseClicked

        Object current = ((ModelTabelePacijenata) tblPacijenti.getModel()).getPacijent(tblPacijenti.getSelectedRow());
        if (current != null && current == lastSelection) {
            tblPacijenti.getSelectionModel().clearSelection();
            tblIstorijaPregleda.setModel(new ModelTabelePregleda());
            lastSelection = null;
        } else {
            lastSelection = current;
        }
        lastSelection2 = null;
   

    }//GEN-LAST:event_tblPacijentiMouseClicked

    private void tblIstorijaPregledaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIstorijaPregledaMouseClicked
        // TODO add your handling code here:
        Object current = ((ModelTabelePregleda) tblIstorijaPregleda.getModel()).getPregled(tblIstorijaPregleda.getSelectedRow());

        if (current != null && current == lastSelection2) {
            tblIstorijaPregleda.getSelectionModel().clearSelection();
            lastSelection2 = null;
        } else {
            lastSelection2 = current;
        }

    }//GEN-LAST:event_tblIstorijaPregledaMouseClicked

    private void txtPretraziPacijentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretraziPacijentaKeyTyped

        resetSelection();
        tblPacijenti.clearSelection();
        tblIstorijaPregleda.setModel(new ModelTabelePregleda());

    }//GEN-LAST:event_txtPretraziPacijentaKeyTyped

    public void resetSelection() {
        lastSelection = null;
        lastSelection2 = null;
    }

    /**
     * @param args the command line arguments
     */
    public void resetPretraga() {
        this.txtPretraziPacijenta.setText("");
    }

    public void setLastSelection(int lastSelection) {
        this.lastSelection = lastSelection;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajNovogPacijenta;
    private javax.swing.JButton btnIzmeniPacijenta;
    private javax.swing.JButton btnObrisiPacijenta;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnPrikaziPregled;
    private javax.swing.JButton btnZakaziPregled;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblIstorijaPregleda;
    private javax.swing.JTable tblPacijenti;
    private javax.swing.JTextField txtPretraziPacijenta;
    // End of variables declaration//GEN-END:variables

   
}
